/**
 * @author uAtomicBoolean
 * @description The command 'play'. This command adds a music to the playlist.
 */

import { CommandInteraction, GuildMember, SlashCommandBuilder, EmbedBuilder } from 'discord.js';


export const data = new SlashCommandBuilder()
	.setName('play')
	.setDescription('Adds a music to the playlist.')
	.addStringOption(option =>
		option
			.setName('music')
			.setDescription('Either a music name or a youtube link.')
			.setRequired(true)
	)


/**
 * The command's handler.
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
export async function execute(interaction: CommandInteraction) {
	const member = interaction.member as GuildMember;
	/*if (!member.voice.channelId) {
		return interaction.reply({ ephemeral: true, embeds: [
			new EmbedBuilder()
				.setTitle('You must be in a voice chat to use this command!')
				.setColor('#FF0000')
		]})
	}*/

	const music = interaction.options.get('music').value as string;
	if (music.includes('https://youtube.com') || music.includes('https://youtu.be')) {
		console.log('link');
	}
	else {
		console.log('title')
	}
}